### ISSUE TITLE
IPFire database.txt as source. 

### ISSUE THREAD

**Issue by MaurUppi** [safing/mmdbmeld#3]
@dhaavi 

https://github.com/safing/mmdbmeld/blob/f16ba11df6d0cc4f2eabef59be535491bf6a453c/source.go#L37-L60

Given you hardcode the file suffix name in L48, thus it's recommended to add a reminder on README.md [ipfire section](https://github.com/safing/mmdbmeld#ipfire)
 > case strings.HasSuffix(input.File, **".ipfire.txt"**) 

Below is my config, the mmdbcheck result `Total=  14462461 Country=0.00%` should be something going wrongly cause the input database.ipfire.txt `139 MB (145,821,355 bytes)` but both 24/32 file size are less than `130KB`.
- I tried `recordSize: 32` but the result is same as 24. 

### can you help to review if anything should be refined? ###

```yml
databases:
  - name: "IPFire IPv4 GeoIP DB"
    mmdb:
      ipVersion: 4 # Note: IPv4 mmdb can only hold IPv4.
      recordSize: 32 # One of 24, 28, 32. Start small, increase if it fails.
    types: # Best to always use the same established keys as MaxMind.
      "network": String
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
      "is_anycast": bool
      "is_satellite_provider": bool
      "is_anonymous_proxy": bool
    fieldMap:
      "net" : "network"
      "aut-num": "autonomous_system_number"
      "name": "autonomous_system_organization"
      "country": "country.iso_code"
      "is-anycast": "is_anycast"
      "is-satellite-provider": "is_satellite_provider"
      "is-anonymous-proxy": "is_anonymous_proxy"
    inputs: # Source data and their mapping.
      # Inputs are processed as listed. Earlier entries are overwritten by later entries.
      - file: "input\\database.ipfire.txt"
    output: output\\ipfire-v4_32.mmdb
    optimize:
      floatDecimals: 2 # Limit floats (eg. coordinates) to decimals for smaller DB size. (0=off, set to -1 to no decimals)
      forceIPVersion: true # Check IPs and discard IPs with the wrong version. (IPv4 and live in IPv6 mmdb)
      maxPrefix: 0 # Remove any network prefixes greater than maxPrefix for smaller DB size. (0=off)
    merge:
      conditionalResets: # Reset set of top level entries if another set is changed.
        # Reset the location entry when the country is changed.
        # If the new entry also has a location, it is kept, but a different country without location resets the location.
        - ifChanged: ["country"]
          reset: ["location"]

```

```shell
PS D:\Github\mmdbmeld> .\cmd\mmdbmeld\mmdbmeld.exe .\config-ipfire.yml

==========
building IPFire IPv4 GeoIP DB
database options set: IPVersion=4 RecordSize=24 (IncludeReservedNetworks=true DisableIPv4Aliasing=true)
database types: autonomous_system_number, autonomous_system_organization, country.iso_code, is_anonymous_proxy, is_anycast, is_satellite_provider
optimizations set: FloatDecimals=2 ForceIPVersion=true MaxPrefix=0
conditional resets: [{IfChanged:[country] Reset:[location]}]
---
processing input\database.ipfire.txt...
inserted 100000 entries - batch in 176ms (2µs/op)
inserted 200000 entries - batch in 124ms (1µs/op)
inserted 300000 entries - batch in 120ms (1µs/op)
inserted 400000 entries - batch in 139ms (1µs/op)
inserted 500000 entries - batch in 139ms (1µs/op)
inserted 600000 entries - batch in 133ms (1µs/op)
inserted 700000 entries - batch in 132ms (1µs/op)
inserted 800000 entries - batch in 133ms (1µs/op)
inserted 900000 entries - batch in 129ms (1µs/op)
inserted 1000000 entries - batch in 142ms (1µs/op)
inserted 1100000 entries - batch in 137ms (1µs/op)
inserted 1109673 entries - batch in 264ms (3µs/op)
---
IPFire IPv4 GeoIP DB finished: inserted 1109673 entries in 2s, resulting in 0.09 MB written to output\\ipfire-v4.mmdb
```

```shell
PS D:\Github\mmdbmeld> .\cmd\mmdbcheck\mmdbcheck.exe all .\output\ipfire-v4.mmdb
loading .\output\ipfire-v4.mmdb with 0.09 MB

Running all checks:

Probing:
..............................................................................................................................................................................................................................................................::
analyzed with 0 lookup errors
Total=  14462461 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%

Network Mask Stats:
          Total=      9323 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  5 Total=         2 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  6 Total=         8 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  7 Total=        21 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  8 Total=        30 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  9 Total=        60 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 10 Total=        81 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 11 Total=       127 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 12 Total=       201 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 13 Total=       262 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 14 Total=       331 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 15 Total=       455 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 16 Total=       540 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 17 Total=       508 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 18 Total=       620 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 19 Total=       751 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 20 Total=       794 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 21 Total=       840 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 22 Total=       883 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 23 Total=       831 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 24 Total=      1978 Country=0.00% Coords=0.00% ASN=0.00% ASOrg=0.00% AC=0.00% SP=0.00% AP=0.00%
```

```
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 1.1.1.1
1.0.0.0/8:
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 1.32.252.111
1.0.0.0/8:
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 212.107.28.52
212.96.0.0/12:
PS D:\Github\mmdbmeld>
```

**Comment by dhaavi** [comment]
Hey @MaurUppi,

The fieldMap is part of the input:

```
    inputs:
      - file: "input/ipfire-geoip.ipfire.txt"
        fieldMap:
          "aut-num": "autonomous_system_number"
          "name": "autonomous_system_organization"
```

Also, the "net" is not part of the data set exposed by the ipfire source, it is implicit in the data set, though, iirc.

**Comment by dhaavi** [comment]
Updated README with your input. Thanks.

**Comment by MaurUppi** [comment]
Report. 

## But What reason may caused `analyzed with 211 lookup errors` ? ##

**Changed config and it works**
<details><summary>Details</summary>
<p>

```yaml
databases:
  - name: "IPFire IPv4 GeoIP DB"
    mmdb:
      ipVersion: 4 # Note: IPv4 mmdb can only hold IPv4.
      recordSize: 32 # One of 24, 28, 32. Start small, increase if it fails.
    types: # Best to always use the same established keys as MaxMind.
    #  "network": String
      "country.iso_code": string
      "autonomous_system_organization": string
      "autonomous_system_number": uint32
      "is_anycast": bool
      "is_satellite_provider": bool
      "is_anonymous_proxy": bool
    inputs: # Source data and their mapping.
      - file: "input\\database.ipfire.txt"
        fieldMap:
          #"net" : "network"
          "aut-num": "autonomous_system_number"
          "name": "autonomous_system_organization"
          "country": "country.iso_code"
          "is-anycast": "is_anycast"
          "is-satellite-provider": "is_satellite_provider"
          "is-anonymous-proxy": "is_anonymous_proxy"
    output: output\\ipfire-v4_32.mmdb
```

</p>
</details> 


**IPFire IPv4 GeoIP DB finished: inserted 1394402 entries in 5s, resulting in 12.59 MB written to output\\ipfire-v4_32.mmdb**

<details><summary>Details</summary>
<p>

```shell
PS D:\Github\mmdbmeld> .\cmd\mmdbmeld\mmdbmeld.exe .\config-ipfire.yml

==========
building IPFire IPv4 GeoIP DB
database options set: IPVersion=4 RecordSize=32 (IncludeReservedNetworks=true DisableIPv4Aliasing=true)
database types: autonomous_system_number, autonomous_system_organization, country.iso_code, is_anonymous_proxy, is_anycast, is_satellite_provider
optimizations set: FloatDecimals=0 ForceIPVersion=false MaxPrefix=0
conditional resets: []
---
processing input\database.ipfire.txt...
inserted 100000 entries - batch in 397ms (4µs/op)
inserted 200000 entries - batch in 284ms (3µs/op)
inserted 300000 entries - batch in 295ms (3µs/op)
inserted 400000 entries - batch in 292ms (3µs/op)
inserted 500000 entries - batch in 290ms (3µs/op)
inserted 600000 entries - batch in 292ms (3µs/op)
inserted 700000 entries - batch in 285ms (3µs/op)
inserted 800000 entries - batch in 281ms (3µs/op)
inserted 900000 entries - batch in 264ms (3µs/op)
inserted 1000000 entries - batch in 273ms (3µs/op)
inserted 1100000 entries - batch in 287ms (3µs/op)
inserted 1200000 entries - batch in 321ms (3µs/op)
inserted 1300000 entries - batch in 303ms (3µs/op)
inserted 1394402 entries - batch in 311ms (3µs/op)
---
IPFire IPv4 GeoIP DB finished: inserted 1394402 entries in 5s, resulting in 12.59 MB written to output\\ipfire-v4_32.mmdb
```

</p>
</details> 



**Total=  14462250 Country=99.72% Coords=0.00% ASN=82.57% ASOrg=77.26% AC=0.54% SP=0.11% AP=0.06%**

```shell
PS D:\Github\mmdbmeld> .\cmd\mmdbcheck\mmdbcheck.exe all .\output\ipfire-v4_32.mmdb
loading .\output\ipfire-v4_32.mmdb with 12.59 MB

Running all checks:

Probing:
..............................................................................................................................................................................................................................................................::
analyzed with 211 lookup errors
Total=  14462250 Country=99.72% Coords=0.00% ASN=82.57% ASOrg=77.26% AC=0.54% SP=0.11% AP=0.06%

Network Mask Stats:
          Total=     35006 Country=99.98% Coords=0.00% ASN=89.38% ASOrg=88.87% AC=14.84% SP=0.23% AP=0.33%
CIDR=/  7 Total=         1 Country=100.00% Coords=0.00% ASN=100.00% ASOrg=100.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  8 Total=         4 Country=100.00% Coords=0.00% ASN=100.00% ASOrg=100.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/  9 Total=         3 Country=100.00% Coords=0.00% ASN=66.67% ASOrg=66.67% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 10 Total=        12 Country=100.00% Coords=0.00% ASN=58.33% ASOrg=58.33% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 11 Total=        22 Country=100.00% Coords=0.00% ASN=72.73% ASOrg=72.73% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 12 Total=        47 Country=100.00% Coords=0.00% ASN=68.09% ASOrg=68.09% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 13 Total=        98 Country=100.00% Coords=0.00% ASN=66.33% ASOrg=66.33% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 14 Total=       169 Country=100.00% Coords=0.00% ASN=68.05% ASOrg=68.05% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 15 Total=       251 Country=100.00% Coords=0.00% ASN=69.32% ASOrg=68.92% AC=0.40% SP=0.00% AP=0.00%
CIDR=/ 16 Total=       432 Country=100.00% Coords=0.00% ASN=74.77% ASOrg=73.61% AC=0.93% SP=0.00% AP=0.00%
CIDR=/ 17 Total=       438 Country=100.00% Coords=0.00% ASN=78.31% ASOrg=76.71% AC=2.28% SP=0.00% AP=0.00%
CIDR=/ 18 Total=       814 Country=100.00% Coords=0.00% ASN=84.28% ASOrg=83.54% AC=5.53% SP=0.00% AP=0.00%
CIDR=/ 19 Total=      1527 Country=100.00% Coords=0.00% ASN=90.31% ASOrg=88.80% AC=13.88% SP=0.00% AP=0.07%
CIDR=/ 20 Total=      2615 Country=100.00% Coords=0.00% ASN=92.20% ASOrg=91.36% AC=19.69% SP=0.08% AP=0.04%
CIDR=/ 21 Total=      3850 Country=100.00% Coords=0.00% ASN=92.13% ASOrg=91.56% AC=14.31% SP=0.10% AP=0.05%
CIDR=/ 22 Total=      5841 Country=100.00% Coords=0.00% ASN=91.47% ASOrg=90.57% AC=24.38% SP=0.10% AP=0.17%
CIDR=/ 23 Total=      6200 Country=100.00% Coords=0.00% ASN=90.68% ASOrg=90.44% AC=18.21% SP=0.39% AP=0.29%
CIDR=/ 24 Total=     12679 Country=99.95% Coords=0.00% ASN=88.47% ASOrg=88.27% AC=10.28% SP=0.35% AP=0.67%
CIDR=/ 31 Total=         1 Country=100.00% Coords=0.00% ASN=100.00% ASOrg=100.00% AC=0.00% SP=0.00% AP=0.00%
CIDR=/ 32 Total=         2 Country=100.00% Coords=0.00% ASN=100.00% ASOrg=100.00% AC=0.00% SP=0.00% AP=0.00%
```


**Checked some IP addr.** 

<details><summary>Details</summary>
<p>

```shell
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 1.1.1.1
1.1.1.0/24:
  autonomous_system_number: 13335
  autonomous_system_organization: CLOUDFLARENET
  country:
    iso_code: AU
  is_anycast: true
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 1.32.252.111
1.32.248.0/21:
  autonomous_system_number: 64050
  autonomous_system_organization: BGP Consultancy Pte Ltd
  country:
    iso_code: AP
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 212.107.28.52
212.107.28.0/22:
  autonomous_system_number: 41378
  autonomous_system_organization: Kirino LLC
  country:
    iso_code: AP
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 119.189.108.244
119.176.0.0/12:
  autonomous_system_number: 4837
  autonomous_system_organization: CHINA UNICOM China169 Backbone
  country:
    iso_code: CN
PS D:\Github\mmdbmeld> .\cmd\mmdbquery\mmdbquery.exe .\output\ipfire-v4_32.mmdb 199.189.108.244
199.189.104.0/21:
  autonomous_system_number: 13213
  autonomous_system_organization: UK-2 Limited
  country:
    iso_code: US
```

</p>
</details>
