### ISSUE TITLE
Memory usage keeps climbing while the mmdbmeld command is running

### ISSUE THREAD

**Issue by nonetallt** [safing/mmdbmeld#5]
As per the post title.

While trying to merge multiple relatively large database files (around 2GB combined), the process eventually dies with:
```
runtime out of memory: cannot allocate X-byte block (Y in use)
fatal error: out of memory
```

My laptop has around 6GB of free RAM for Go to work with but the process seems to die with that error before getting there (premature OOM). Any chances of improving gc or otherwise reducing the application memory footprint? I don't think this is an issue with the writer library itself, since there are no mentions of people encountering many issues with memory even with a large row count.

Edit: Also tested on a 16GB virtual machine, ran out of memory after some 30 million rows. The memory efficiency makes this tool pretty much unusable for working with any medium size files.

**Comment by dhaavi** [comment]
Well, the this tool pretty much reads the files line by line, converts it according to the config and then feeds the line immediately into the writer library.

I would definitely expect it to need a couple times the memory of the input size. Though I would have guessed that 16GB should have been enough for 2GB of input.

Can you split the data into multiple databases? Eg. one for IPv4, one for IPv6.

Maybe there is an issue with the data conversion. Can you share your config?

**Comment by nonetallt** [comment]
> Can you split the data into multiple databases? Eg. one for IPv4, one for IPv6.

Isn't the entire point of the library to be able to merge databases? Why would you want to split something you want to query once into multiple different files?

> Maybe there is an issue with the data conversion. Can you share your config?

That could be the case, but I'm not sure if that would account for what looks like a memory leak.

```
---
databases:
- name: database
  mmdb:
    ipVersion: 6
    recordSize: 34
  types:
    from: string
    to: string
    net: string
    asn.asn: string
    asn.domain: string
    asn.name: string
    asn.type: string
    asn.country: string
    country.name: string
    country.iso_3166_2: string
    continent.name: string
    continent.code: string
    city.name: string
    region.name: string
    latitude: float32
    longitude: float32
    timezone: string
    company.name: string
    company.domain: string
    company.type: string
    company.asn: string
    company.as_name: string
    company.as_domain: string
    company.as_type: string
    is_proxy: bool
    is_hosting: bool
    is_robot: bool
    is_tor: bool
    is_vpn: bool
  inputs:
  - file: company.csv
    fields:
    - from
    - to
    - '-'
    - company.name
    - company.domain
    - company.type
    - company.asn
    - company.as_name
    - company.as_domain
    - company.as_type
    - '-'
  - file: asn.csv
    fields:
    - from
    - to
    - '-'
    - asn.asn
    - asn.domain
    - asn.name
    - asn.type
    - '-'
  - file: location.csv
    fields:
    - from
    - to
    - '-'
    - city.name
    - region.name
    - country.iso_3166_2
    - latitude
    - longitude
    -  '-'
    - timezone
  - file: privacy.transformed.csv
    fields:
    - from
    - to
    - is_proxy
    - is_hosting
    - is_robot
    - is_tor
    - is_vpn
  output: database.mmdb
  optimize:
    floatDecimals: 4
    forceIPVersion: false
    maxPrefix: 0
...
```

> I would definitely expect it to need a couple times the memory of the input size. Though I would have guessed that 16GB should have been enough for 2GB of input.

It was way worse than even that. I booted up a 200GB RAM machine just to see what would happen. To produce an output file with the size of around 2,5GB (from orginal data of ~2GB), it ate up 77GB of RAM.  The total row count was somewhere around ~165 million.
